### ISSUE TITLE
`SHADOW_STYLE` not defined with dev server

### ISSUE THREAD

**Issue by panta82** [hood/vite-plugin-shadow-style#5]
It seems `SHADOW_STYLE` is not defined when running the dev server (`npm run dev`), only in production builds.

Is this by design, or am I doing something wrong? My experimental config is pretty vanilla:

```
import { shadowStyle } from "vite-plugin-shadow-style";

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), shadowStyle()],
  build: {
    rollupOptions: {
      plugins: [react(), shadowStyle()],
    },
  },
});
```

**Comment by hood** [comment]
Yes, I've currently only used this plugin in builds and never in dev mode. 

To give you some context, the plugin was born because I needed to distribute widgets in single file bundles to sprinkle interactivity over an old static website. In my setup I use React to build the components and, to take advantage of HMR etc, I use a different config for dev mode where I simply mount them as components in a SPA. 

I'm surely interested in getting this to work in a dev environment, so keep an eye on the updates, and feel free to contribute if you feel like it, I'm still learning the inner workings of Vite.
